# Generated by Django 4.2.3 on 2023-07-06 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=200)),
                ('task_description', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateField()),
                ('priority', models.CharField(choices=[('low', 'Малый'), ('medium', 'Средний'), ('high', 'Высокий')], max_length=10)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
