# Generated by Django 4.2.3 on 2023-07-06 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_rename_deadline_todolist_deadlin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolist',
            old_name='deadlin',
            new_name='deadline',
        ),
        migrations.RemoveField(
            model_name='todolist',
            name='created_date',
        ),
    ]
