# Generated by Django 4.2.3 on 2023-07-06 01:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_rename_deadlin_todolist_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='start_deadline',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
