# Generated by Django 4.2.3 on 2023-07-06 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0005_todolist_start_deadline'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todolist',
            options={'ordering': ['-start_deadline', '-priority'], 'verbose_name_plural': 'Список задач'},
        ),
        migrations.AlterField(
            model_name='todolist',
            name='priority',
            field=models.CharField(choices=[(1, 'Малый'), (3, 'Высокий'), (1, 'Средний')], max_length=10),
        ),
    ]
